{% set name = "pyiron_atomistics" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5df7644aeadcde84b8514b078feb4de62d074ab80162dc8f74d153fe2e4dfd83

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - pylammpsmpi
    - ase
    - atomistics
    - defusedxml
    - h5py
    - matplotlib-base
    - mendeleev
    - mp-api
    - numpy >=1.26.0
    - pandas
    - phonopy
    - pint
    - pyiron_base
    - scipy
    - seekpath
    - scikit-learn
    - spglib
    - structuretoolkit
    - versioneer
    - toml
  run:
    - python >=3.8
    - ase ==3.22.1
    - atomistics >=0.1.12,<=0.1.26
    - defusedxml >=0.7.0,<=0.7.1
    - h5py >=3.9.0,<=3.11.0
    - matplotlib-base >=3.5.3,<=3.8.4
    - mendeleev >=0.12.0,<=0.15.0
    - mp-api >=0.37.0,<=0.41.2
    - numpy >=1.26.0,<=1.26.4
    - pandas >=2.0.3,<=2.2.2
    - phonopy >=2.20.0,<=2.22.1
    - pint >=0.18,<=0.23
    - pyiron_base >=0.7.7,<=0.8.2
    - pylammpsmpi >=0.2.7,<=0.2.15
    - scipy >=1.11.1,<=1.13.0
    - scikit-learn >=1.2.1,<=1.4.2
    - seekpath >=1.9.5,<=2.1.0
    - spglib >=2.0.2,<=2.4.0
    - structuretoolkit >=0.0.19,<=0.0.22

test:
  imports:
    - pyiron_atomistics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_atomistics
  summary: pyiron - an integrated development environment (IDE) for computational materials science.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
