{% set name = "pyiron_atomistics" %}
{% set version = "0.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e860e2f45e9ac95ab0eafefb9ff1fdccf98de97775c5a70d289bbe47e79c3468

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - pylammpsmpi >=0.2.7,<=0.2.9
    - python >=3.8
    - ase ==3.22.1
    - atomistics ==0.1.12
    - defusedxml >=0.7.0,<=0.7.1
    - h5py >=3.9.0,<=3.10.0
    - matplotlib-base >=3.5.3,<=3.8.2
    - mendeleev >=0.12.0,<=0.14.0
    - mp-api >=0.37.0,<=0.39.0
    - numpy >=1.26.0,<=1.26.2 # for numba and pytorch compatibility
    - pandas >=2.0.3,<=2.1.3
    - phonopy ==2.20.0
    - pint >=0.18,<=0.22
    - pyiron_base ==0.6.11
    - scipy >=1.11.1,<=1.11.4
    - seekpath >=1.9.5,<=2.1.0
    - scikit-learn >=1.2.1,<=1.3.2
    - spglib >=2.0.2,<=2.1.0
    - structuretoolkit ==0.0.15
    - python-blosc2  # for pytables

test:
  imports:
    - pyiron_atomistics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_atomistics
  summary: pyiron - an integrated development environment (IDE) for computational materials science.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
