{% set name = "pyiron_atomistics" %}
{% set version = "0.3.1" %}
{% set sha256 = "54a5cfa57f9e231e6bddd414bdddf70ba8c8bdfaaa86e8ef73596e6ac4a57a9c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron-atomistics-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip

  run:
    - python >=3.8
    - ase >=3.22.1
    - defusedxml >=0.7.1
    - h5py >=2.10.0  # for tensorflow compatibility
    - matplotlib-base >=3.7.1
    - mendeleev >=0.13.1
    - mp-api >=0.33.3
    - numpy >=1.19.5  # for numba and pytorch compatibility
    - pandas >=2.0.2
    - phonopy >=2.19.1
    - pint >=0.21  # for backwards compatibility to python 3.8
    - pymatgen >=2020.12.31  # for pytorch compatibility
    - pyiron_base >=0.6.1
    - pyscal >=2.10.18
    - scipy >=1.10.1
    - seekpath >=2.1.0
    - scikit-learn >=1.2.2
    - spglib >=2.0.2
    - structuretoolkit =0.0.3
    - pyiron-data >=0.0.22

test:
  imports:
    - pyiron_atomistics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_atomistics
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Atomistics plugin for pyiron - an integrated development environment (IDE) for computational materials science.
  description: |
    pyiron was initially developed in the Computational Materials Design department of Joerg Neugebauer at the
    Max Planck Insitut für Eisenforschung (Max Planck Insitute for iron research) as a framework for ab initio
    thermodynamics. In collaboration with the Interdisciplinary Centre for Advanced Materials Simulation (ICAMS)
    the framework was recently extended for high throughput applications resulting in the opensource release of
    pyiron.
  doc_url: https://pyiron.org
  dev_url: https://github.com/pyiron

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
