{% set name = "pyiron_atomistics" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron-atomistics-{{ version }}.tar.gz
  sha256: e57b82aa3435fc34d663349f8bb5b0050c4b058608482601659900a05dbd804b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ase >=3.22.1
    - atomistics >=0.1.2
    - defusedxml >=0.7.1
    - h5py >=3.10.0
    - matplotlib-base >=3.8.1
    - mendeleev >=0.14.0
    - mp-api >=0.37.5
    - numpy >=1.26.0  # for numba and pytorch compatibility
    - pandas >=2.1.3
    - phonopy >=2.20.0
    - pint >=0.22
    - pyiron_base >=0.6.9
    - scipy >=1.11.3
    - seekpath >=2.1.0
    - scikit-learn >=1.3.2
    - spglib >=2.1.0
    - structuretoolkit >=0.0.12

test:
  imports:
    - pyiron_atomistics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_atomistics
  summary: pyiron - an integrated development environment (IDE) for computational materials science.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
