{% set name = "pyiron_atomistics" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron-atomistics-{{ version }}.tar.gz
  sha256: 2e1890c780b06923480ad2d0ba466986975420f38aec3aae0e3f03e5478ba3d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ase >=3.22.1
    - atomistics >=0.0.6
    - defusedxml >=0.7.1
    - h5py >=3.10.0
    - matplotlib-base >=3.8.0
    - mendeleev >=0.14.0
    - mp-api >=0.37.5
    - numpy >=1.24.4  # for numba and pytorch compatibility
    - pandas >=2.1.1
    - phonopy >=2.20.0
    - pint >=0.22
    - pyiron_base >=0.6.8
    - scipy >=1.11.3
    - seekpath >=2.1.0
    - scikit-learn >=1.3.1
    - spglib >=2.1.0
    - structuretoolkit >=0.0.11

test:
  imports:
    - pyiron_atomistics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_atomistics
  summary: pyiron - an integrated development environment (IDE) for computational materials science.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
