{% set name = "pyiron_atomistics" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a23354939164531e29e98814c5a4b72ab35574891331da6437f5bea5b98550b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - pip
    - pylammpsmpi
    - ase
    - atomistics
    - defusedxml
    - h5py
    - matplotlib-base
    - mendeleev
    - mp-api
    - numpy >=1.26.0
    - pandas
    - phonopy
    - pint
    - pyiron_base
    - pyiron_snippets
    - scipy
    - seekpath
    - scikit-learn
    - spglib
    - structuretoolkit
    - versioneer
    - toml
  run:
    - pyiron_snippets >=0.1.1,<=0.1.2
    - python >=3.9,<3.13
    - ase >=3.22.1,<=3.23.0
    - atomistics >=0.1.27,<=0.1.29
    - defusedxml >=0.7.0,<=0.7.1
    - h5py >=3.9.0,<=3.11.0
    - matplotlib-base >=3.5.3,<=3.8.4
    - mendeleev >=0.12.0,<=0.17.0
    - mp-api >=0.37.0,<=0.41.2
    - numpy >=1.26.0,<=1.26.4
    - pandas >=2.0.3,<=2.2.2
    - phonopy >=2.20.0,<=2.24.2
    - pint >=0.18,<=0.24
    - pyiron_base ==0.9.4
    - pylammpsmpi >=0.2.18,<=0.2.19
    - scipy >=1.11.1,<=1.13.1
    - scikit-learn >=1.2.1,<=1.5.0
    - seekpath >=1.9.5,<=2.1.0
    - spglib >=2.0.2,<=2.4.0
    - structuretoolkit >=0.0.19,<=0.0.25

test:
  imports:
    - pyiron_atomistics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_atomistics
  summary: pyiron - an integrated development environment (IDE) for computational materials science.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
