travis:
  secure:
    BINSTAR_TOKEN: CCg5ksVVube5umijoqT2tTBM05LvjhyZbvNSz35AdOnxW1s+DKQvo8Uue84DP3peZpNDz6F7lcx1NgiZKHyiPZpEoLVV9xP2L2KjFnTajPzs7+EOkfjfBcLuOvdYTjfEWpxqwf1icB79lVO368mR1/FvPLVK9rHXndHWciyMOQLY4plZva6aksVxB1gfJwFC8dYW+J8ElswTB1G5Z3FvLvOi30jkCdDsNnwjiwGQapL8KmkfsXyxVmIxoH8lonN0zfqqx/bnzyUYPW7GPyeYTEnAkBEg5pYq/kpzsB+9xpb/UYhVBzQRZzXxmxcnROo/mJOGQ961ytM0mrSwdc7esNvpKDWWo31cWkNQw7OtW3OZrHi3eUA1Y+Tqt/OPHHMFWfT07KBnKy8zM8KHw37cfw04CgY0Gn0Xc1ygxuQgPh4wSzzEDPcp0MdgVGa+/LCNS3EjAii2vmgdg2GbzRLn+GLGhk3djmXLzggqpcRsv1KxiVYMzsSoaTWKPmLsx7H1tJq9mjAgzO6nYyH8w1jGUJDfRS7DIuUvb+UTE1gvEZ6l1QaFNt6FDl31SfPRUWFGVxaB+WniDe0Nfzh9wrYb/6xsiQ7LhfnpvfdGtVzYGgMMkd/etWly1TSbT21vrbNRGEaX8tVEoBB/szRm0cZcA3/wBFlYLlwur7S30ehXEGc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
